FROM dev:base

RUN mkdir -p ~/.local/lib ~/.local/bin &&\
    VERSION=$(curl -s https://api.github.com/repos/coder/code-server/releases/latest | grep -o '"tag_name": ".*"' | cut -d'"' -f4 | cut -c 2-) &&\
    curl -fL https://github.com/coder/code-server/releases/download/v$VERSION/code-server-$VERSION-linux-amd64.tar.gz | tar -C ~/.local/lib -xz &&\
    mv ~/.local/lib/code-server-$VERSION-linux-amd64 ~/.local/lib/code-server-$VERSION &&\
    ln -s ~/.local/lib/code-server-$VERSION/bin/code-server ~/.local/bin/code-server &&\
    sed  -i '2i\  "extensionsGallery": {"serviceUrl": "https://marketplace.visualstudio.com/_apis/public/gallery","cacheUrl": "https://vscode.blob.core.windows.net/gallery/index", "itemUrl": "https://marketplace.visualstudio.com/items","controlUrl": "", "recommendationsUrl": ""},'  ~/.local/lib/code-server-$VERSION/lib/vscode/product.json

CMD ["/root/.local/bin/code-server"]