services:
  dev:
    image: bestrui/dev
    network_mode: host
    privileged: true
    volumes:
      - /home/bestrui/dev:/root/.vscode-server
      - ./:/workplace
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker