FROM bestrui/dev:base

SHELL ["/bin/bash", "-c"] 

RUN mkdir /var/run/sshd && \
    sed -i 's/#Port 22/Port 2222/' /etc/ssh/sshd_config &&\
    sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config &&\
    chsh -s /usr/bin/zsh

CMD ["/usr/sbin/sshd", "-D"]
